version: '3.8'
services:
    web:
        build: .
        command: python manage.py runserver 0.0.0.0:8080
        ports:
            - 8080:8080
        depends_on:
            - migration
            
    migration:
        build: .
        command: python manage.py migrate --noinput
        
    task_crawler:
        build: .
        command: python manage.py runscript crawler
        depends_on:
            - web
