# Generated by Django 4.1.1 on 2022-09-19 10:43

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone_number', models.CharField(max_length=11, validators=[django.core.validators.RegexValidator(message="Phone number format must be: '7XXXXXXXXXX'. Where X is digit from 0 to 9.", regex='7\\d{10}$')])),
                ('phone_code', models.IntegerField(default=7)),
                ('tag', models.CharField(blank=True, max_length=50, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Mailing',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('started_at', models.DateTimeField(auto_now_add=True)),
                ('ended_at', models.DateTimeField()),
                ('text', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('status', models.IntegerField(choices=[(1, 'is_sent'), (0, 'not_sent')], default=0)),
                ('from_mailing', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mailing_app.mailing')),
                ('to_client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mailing_app.client')),
            ],
        ),
    ]
