# Generated by Django 4.1.1 on 2022-09-19 11:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mailing_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mailing',
            name='ended_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='mailing',
            name='text',
            field=models.TextField(max_length=500),
        ),
    ]
