# Generated by Django 4.1.1 on 2022-09-20 10:43

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mailing_app', '0008_alter_mailing_ended_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='time_zone',
            field=models.CharField(blank=True, default='UTC', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='mailing',
            name='ended_at',
            field=models.DateTimeField(default=datetime.datetime(2022, 9, 20, 13, 53, 12, 861596, tzinfo=datetime.timezone.utc)),
        ),
    ]
