# Generated by Django 4.1.1 on 2022-09-25 18:39

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mailing_app', '0009_client_time_zone_alter_mailing_ended_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mailing',
            name='ended_at',
            field=models.DateTimeField(default=datetime.datetime(2022, 9, 25, 21, 49, 2, 883690, tzinfo=datetime.timezone.utc)),
        ),
    ]
