# Generated by Django 4.1.1 on 2022-09-26 07:30

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mailing_app', '0014_alter_mailing_ended_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mailing',
            name='ended_at',
            field=models.DateTimeField(default=datetime.datetime(2022, 9, 26, 10, 40, 53, 154087, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='mailing',
            name='started_at',
            field=models.DateTimeField(default=datetime.datetime(2022, 9, 26, 10, 30, 53, 154087)),
        ),
    ]
